import type { Request } from '../../models';

export const earlyGameChainDefs: Request[] = [
  // === CHAIN 1: MUDSLIDE ===
  {
    id: 'CHAIN_MUDSLIDE_START',
    chainId: 'MUDSLIDE',
    chainRole: 'start',
    title: 'When the Rains Come',
    text: 'Three days of relentless downpour have turned the eastern fields to churning mud. A mudslide has buried two terraces of winter crops beneath clay and stone. Feldric reports the damage — a quarter of the food stores lost unless you act swiftly. The farmers stand in the rain, watching their livelihood vanish into brown water.',
    portraitId: 'military_advisor',
    options: [
      { text: 'REPAIR & RESTORE', effects: { gold: -15, farmers: -2 } },
      { text: 'MOVE TO HIGHER LAND', effects: { gold: -5, farmers: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'MUDSLIDE_MEMBER_REPAIR', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'MUDSLIDE_MEMBER_RELOCATE', weight: 1 }] },
    ],
  },
  {
    id: 'MUDSLIDE_MEMBER_REPAIR',
    chainId: 'MUDSLIDE',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'Breaking Ground',
    text: 'The farmers work dawn to dusk, hauling clay and resetting stone markers. Markweard watches from the hillside — he murmurs something about old magic woven into the soil, how the mud itself resists healing. Three days in, the first crops sprout again, but sickness runs through them like a black thread. Markweard offers a cure ritual, but it will cost more gold and demand his full attention.',
    portraitId: 'mage_advisor',
    options: [
      { text: 'ACCEPT THE LOSS', effects: { satisfaction: -2, gold: 5 } },
      { text: 'INVOKE CURE RITUAL', effects: { gold: -8, authority: 2 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 3, candidates: [{ requestId: 'MUDSLIDE_END_PARTIAL', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'MUDSLIDE_END_RESTORED', weight: 1 }] },
    ],
  },
  {
    id: 'MUDSLIDE_MEMBER_RELOCATE',
    chainId: 'MUDSLIDE',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'Seeking Higher Ground',
    text: 'The farmers push northward into the drier terraces, clearing brush and turning new soil. The work is hard but the mood is hopeful — fresh land, fresh starts. Yet Feldric warns that you are spreading thin, and the old terraces will lie fallow for seasons. You can push further into untamed land for more yield, or fortify what you have.',
    portraitId: 'farmer',
    options: [
      { text: 'PUSH FURTHER NORTH', effects: { farmers: -1, satisfaction: 2, gold: -3 } },
      { text: 'FORTIFY NEW PLOTS', effects: { gold: -7, farmers: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'MUDSLIDE_END_EXPANSION', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 3, candidates: [{ requestId: 'MUDSLIDE_END_SECURE', weight: 1 }] },
    ],
  },
  {
    id: 'MUDSLIDE_END_PARTIAL',
    chainId: 'MUDSLIDE',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 30,
    title: 'Bitter Harvest',
    text: 'You harvest what you can from the diseased crops — enough to feed the village, but barely. The granaries hold less than before. The farmers look to you with hollow eyes, wondering if next season will be kinder. The eastern terraces bear scars that will take years to heal.',
    portraitId: 'farmer',
    options: [
      { text: 'WE ENDURE', effects: { satisfaction: -1 } },
      { text: 'RATION CAREFULLY', effects: { gold: -5, health: 1 } },
    ],
  },
  {
    id: 'MUDSLIDE_END_RESTORED',
    chainId: 'MUDSLIDE',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 35,
    title: 'The Fields Live Again',
    text: 'Markweard\'s ritual weaves together earth and sky. The black sickness fades like morning mist. The crops surge back with almost unnatural vigor — a full harvest, perhaps better than before. The farmers cheer your name. Markweard simply nods and returns to his tower, muttering about debts owed to the soil.',
    portraitId: 'mage_advisor',
    options: [
      { text: 'THANK MARKWEARD', effects: { satisfaction: 3, health: 1 } },
      { text: 'CELEBRATE THE HARVEST', effects: { satisfaction: 2, gold: 5 } },
    ],
  },
  {
    id: 'MUDSLIDE_END_EXPANSION',
    chainId: 'MUDSLIDE',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 32,
    title: 'Into Untamed Land',
    text: 'The northern plots flourish, but the old fields lie barren and forgotten. You have gained ground but lost stability. Some praise your boldness; others mutter of overreach. The village stretches further than ever before, and the roads between plots grow long and lonely.',
    portraitId: 'farmer',
    options: [
      { text: 'FORTUNE FAVORS THE BOLD', effects: { satisfaction: 2, gold: 3 } },
      { text: 'CONSOLIDATE WHAT WE HAVE', effects: { satisfaction: 1, authority: 1 } },
    ],
  },
  {
    id: 'MUDSLIDE_END_SECURE',
    chainId: 'MUDSLIDE',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 28,
    title: 'Foundation Laid',
    text: 'The new plots are strong, terraced with care, and protected from future slides. The farmers work with renewed purpose. You have not regained what was lost, but you have built something lasting. The village speaks of your steady hand with quiet respect.',
    portraitId: 'farmer',
    options: [
      { text: 'STEADY AS SHE GOES', effects: { satisfaction: 2, authority: 1 } },
      { text: 'PLAN FOR NEXT SEASON', effects: { satisfaction: 1, fireRisk: -1 } },
    ],
  },

  // === CHAIN 2: STRAY_DOG ===
  {
    id: 'CHAIN_STRAY_DOG_START',
    chainId: 'STRAY_DOG',
    chainRole: 'start',
    title: 'The Beast in the Square',
    text: 'A scarred, wild dog has made the village square its territory. It snapped at a child yesterday, tore clothing and drew blood. Mothers now keep their young indoors. Feldric urges swift action — either kill the beast or drive it away before someone is seriously injured. Dunhild watches the dog from a distance and shakes her head. "It\'s starving. It\'s afraid."',
    portraitId: 'military_advisor',
    options: [
      { text: 'ORGANIZE A HUNT', effects: { gold: -5, authority: 2 } },
      { text: 'ATTEMPT TO TAME', effects: { gold: -3, satisfaction: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STRAY_DOG_MEMBER_HUNT', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STRAY_DOG_MEMBER_TAME', weight: 1 }] },
    ],
  },
  {
    id: 'STRAY_DOG_MEMBER_HUNT',
    chainId: 'STRAY_DOG',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Hunt Begins',
    text: 'Feldric leads a band of men into the outlying woods where the dog has been spotted. Torches light the undergrowth. For an hour there is silence — then a sudden cry. The dog is cornered in a ravine, injured and snarling. Its ribs show through matted fur. Even Feldric hesitates.',
    portraitId: 'military_advisor',
    options: [
      { text: 'FINISH IT SWIFTLY', effects: { satisfaction: -1, authority: 2 } },
      { text: 'BRING IT BACK ALIVE', effects: { health: -2, satisfaction: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 0, delayMaxTicks: 2, candidates: [{ requestId: 'STRAY_DOG_END_CLEAN_KILL', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 0, delayMaxTicks: 2, candidates: [{ requestId: 'STRAY_DOG_END_TRAGEDY', weight: 1 }] },
    ],
  },
  {
    id: 'STRAY_DOG_MEMBER_TAME',
    chainId: 'STRAY_DOG',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Patient Hand',
    text: 'Dunhild takes the lead, leaving meat and bread in the square each dawn. The dog watches from the shadows, wary but hungry. After three days, it approaches within arm\'s reach. Dunhild does not move. The dog sniffs her outstretched palm and hesitates. "We can feed it into trust," she says, "or collar it now while it\'s close."',
    portraitId: 'healer',
    options: [
      { text: 'OFFER MORE FOOD', effects: { gold: -5, satisfaction: 1 } },
      { text: 'MAKE A COLLAR', effects: { gold: -8, authority: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STRAY_DOG_END_TAMED', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STRAY_DOG_END_DEFIANT', weight: 1 }] },
    ],
  },
  {
    id: 'STRAY_DOG_END_CLEAN_KILL',
    chainId: 'STRAY_DOG',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 35,
    title: 'The Debt Paid',
    text: 'The beast is gone. Children play in the square again without fear. But in the tavern, some mutter about mercy and waste — a creature that could have been saved. The village is safer, yet not wholly at peace with the killing.',
    portraitId: 'military_advisor',
    options: [
      { text: 'IT WAS NECESSARY', effects: { satisfaction: 1, authority: 1 } },
      { text: 'BURY IT PROPERLY', effects: { satisfaction: 2 } },
    ],
  },
  {
    id: 'STRAY_DOG_END_TRAGEDY',
    chainId: 'STRAY_DOG',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 40,
    title: 'A Darker Ending',
    text: 'The dog is brought back caged and furious. On the second night, a child approaches the cage out of curiosity. The dog lunges through the bars. The child survives — barely — but the scar runs deep, and so does the village\'s anger at your mercy. The dog is killed the next morning. No one protests.',
    portraitId: 'children',
    options: [
      { text: 'WE TRIED', effects: { satisfaction: -4, health: -2 } },
      { text: 'STRENGTHEN THE FENCES', effects: { satisfaction: -3, gold: -5 } },
    ],
  },
  {
    id: 'STRAY_DOG_END_TAMED',
    chainId: 'STRAY_DOG',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 32,
    title: 'A Companion Found',
    text: 'The dog becomes Dunhild\'s shadow, loyal and gentle. Children who once feared the square now gather to pet the scarred beast, and their faces shine with wonder. A creature of violence has become a keeper of peace. The village speaks of your patience with quiet admiration.',
    portraitId: 'healer',
    options: [
      { text: 'WELL DONE, DUNHILD', effects: { satisfaction: 4, health: 1 } },
      { text: 'NAME THE DOG', effects: { satisfaction: 3, authority: 1 } },
    ],
  },
  {
    id: 'STRAY_DOG_END_DEFIANT',
    chainId: 'STRAY_DOG',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 30,
    title: 'The Wild Heart Remains',
    text: 'The collar sits uneasy on the dog\'s neck. It stays near Dunhild but will not be fully tamed. It snaps at strangers and refuses the pen. You have not defeated the beast, but you have given it a home — and it has given you a guardian with a price. Dunhild says it will soften with time. The village is not convinced.',
    portraitId: 'healer',
    options: [
      { text: 'GIVE IT TIME', effects: { satisfaction: 2, authority: 1 } },
      { text: 'KEEP CHILDREN AWAY', effects: { satisfaction: 1, health: 1 } },
    ],
  },

  // === CHAIN 3: WELL_POISONED ===
  {
    id: 'CHAIN_WELL_POISONED_START',
    chainId: 'WELL_POISONED',
    chainRole: 'start',
    title: 'Sickness in the Water',
    text: 'The village well tastes of copper and rot. Three families have taken ill with stomach cramps and fever. Dunhild suspects poisoning — either deliberate or from a dead animal in the shaft. "We must act quickly, my lord. Either find the source, or abandon the well and dig a new one."',
    portraitId: 'healer',
    options: [
      { text: 'INVESTIGATE THE WELL', effects: { gold: -5, authority: 1 } },
      { text: 'DIG A NEW ONE', effects: { gold: -25, farmers: -1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'WELL_POISONED_MEMBER_INVESTIGATE', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'WELL_POISONED_MEMBER_DIG', weight: 1 }] },
    ],
  },
  {
    id: 'WELL_POISONED_MEMBER_INVESTIGATE',
    chainId: 'WELL_POISONED',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'Into the Dark',
    text: 'Dunhild and Garthric lower a torch into the well\'s throat. The shaft is deep, cold, and silent. At the bottom, they find a rotting deer carcass — but also scratches on the stone, as if something was forced down deliberately. Garthric speaks of malice. "Was it accident, or did someone wish us ill? Seeking enemies would show strength, but it could also tear the village apart."',
    portraitId: 'village_priest',
    options: [
      { text: 'ASSUME ACCIDENT', effects: { satisfaction: 2, health: 1 } },
      { text: 'HUNT FOR ENEMIES', effects: { authority: 3, gold: -10, satisfaction: -1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'WELL_POISONED_END_ACCIDENT', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'WELL_POISONED_END_WITCH_HUNT', weight: 1 }] },
    ],
  },
  {
    id: 'WELL_POISONED_MEMBER_DIG',
    chainId: 'WELL_POISONED',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'Breaking New Ground',
    text: 'The farmers set to work north of the village, digging with purpose. Two days in, they strike water — clear, cold, sweet. But as the new well fills, a strange rumbling echoes from the earth below. An old shaft, perhaps, or something older still. The ground feels unstable. You can seal the rumbling and use the well as-is, or investigate what lies beneath.',
    portraitId: 'farmer',
    options: [
      { text: 'SEAL AND CONTINUE', effects: { gold: -8, satisfaction: 1 } },
      { text: 'INVESTIGATE BELOW', effects: { gold: -12, health: -2 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 1, delayMaxTicks: 2, candidates: [{ requestId: 'WELL_POISONED_END_FRESH', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'WELL_POISONED_END_DISCOVERY', weight: 1 }] },
    ],
  },
  {
    id: 'WELL_POISONED_END_ACCIDENT',
    chainId: 'WELL_POISONED',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 28,
    title: 'A Natural Cause',
    text: 'The old well is cleaned and blessed by Garthric. The sickness fades within days. Life returns to normal. Some whisper that you were too quick to trust in chance, but the problem is solved and the village drinks deeply once more.',
    portraitId: 'village_priest',
    options: [
      { text: 'BLESS THE WATER', effects: { health: 2, satisfaction: 1 } },
      { text: 'POST A GUARD ANYWAY', effects: { health: 2, authority: 1 } },
    ],
  },
  {
    id: 'WELL_POISONED_END_WITCH_HUNT',
    chainId: 'WELL_POISONED',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 40,
    title: 'Suspicion\'s Harvest',
    text: 'You find no poisoner. But in the chaos of accusation, an innocent elder is blamed and expelled from the village in shame. The true mystery remains unsolved. The well is cleaned, but trust is broken. Neighbors eye each other with suspicion, and your name is spoken with doubt.',
    portraitId: 'elder',
    options: [
      { text: 'THE PRICE OF CAUTION', effects: { satisfaction: -4, authority: -2 } },
      { text: 'RECALL THE ELDER', effects: { satisfaction: -2, gold: -5 } },
    ],
  },
  {
    id: 'WELL_POISONED_END_FRESH',
    chainId: 'WELL_POISONED',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 32,
    title: 'New Waters',
    text: 'The new well flows strong and clean. The old well is sealed and forgotten. Your swift action has saved the village from sickness and fear. The cost was high, but the people see you as one who solves problems when lesser leaders would hesitate.',
    portraitId: 'farmer',
    options: [
      { text: 'MARK THE NEW WELL', effects: { satisfaction: 3, health: 2 } },
      { text: 'PLAN FOR DROUGHT', effects: { satisfaction: 2, authority: 1 } },
    ],
  },
  {
    id: 'WELL_POISONED_END_DISCOVERY',
    chainId: 'WELL_POISONED',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 35,
    title: 'Secrets of Stone',
    text: 'Below the new well lies an ancient chamber — worked stone, runes in a tongue no one speaks, and shelves that once held things long decayed. A relic of the old world. Markweard arrives to study the find, muttering of old magic and older powers. You have uncovered a mystery far deeper than a poisoned well.',
    portraitId: 'mage_advisor',
    options: [
      { text: 'LET MARKWEARD STUDY IT', effects: { satisfaction: 2, authority: 2 } },
      { text: 'SEAL IT AND FORGET', effects: { satisfaction: 1, health: 2 } },
    ],
  },

  // === CHAIN 4: STOLEN_TOOLS ===
  {
    id: 'CHAIN_STOLEN_TOOLS_START',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'start',
    title: 'A Neighbor\'s Theft',
    text: 'Old Aelred accuses his neighbor Thornweard of stealing his toolset — shovel, hoe, and plow blade, worth three months of trade. Thornweard denies it hotly. Both men demand your judgment. Barnwulf advises caution: "Investigate first, my lord, or make a swift decision and let the chips fall. But know that the village is watching."',
    portraitId: 'advisor',
    options: [
      { text: 'INVESTIGATE FAIRLY', effects: { gold: -3, authority: 1 } },
      { text: 'JUDGE SWIFTLY', effects: { authority: 2, satisfaction: -1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STOLEN_TOOLS_MEMBER_INVESTIGATE', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STOLEN_TOOLS_MEMBER_JUDGE', weight: 1 }] },
    ],
  },
  {
    id: 'STOLEN_TOOLS_MEMBER_INVESTIGATE',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Evidence Gathers',
    text: 'You search both farms with care. Aelred\'s tools are not in Thornweard\'s shed — but you find something else: a half-repaired plow blade hidden in Aelred\'s own barn, identical markings, and Thornweard\'s name scratched faintly on the handle. The accusation was false. Aelred either lied or was deeply confused.',
    portraitId: 'farmer',
    options: [
      { text: 'EXPOSE THE LIE', effects: { authority: 3, satisfaction: 1 } },
      { text: 'QUIETLY ADVISE AELRED', effects: { gold: 5, satisfaction: 2, authority: -1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 1, delayMaxTicks: 2, candidates: [{ requestId: 'STOLEN_TOOLS_END_PUBLIC_SHAME', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 1, delayMaxTicks: 2, candidates: [{ requestId: 'STOLEN_TOOLS_END_MERCY', weight: 1 }] },
    ],
  },
  {
    id: 'STOLEN_TOOLS_MEMBER_JUDGE',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Verdict Given',
    text: 'You gather both men in the square and declare: the accused must pay back the tools or face labor service to the village. Thornweard\'s face goes pale — he protests, weeps, swears innocence. But you have spoken, and the crowd awaits your will. Barnwulf shifts uncomfortably at your side.',
    portraitId: 'advisor',
    options: [
      { text: 'STAND FIRM', effects: { authority: 2, satisfaction: -2 } },
      { text: 'OFFER COMPROMISE', effects: { gold: -8, satisfaction: 1 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STOLEN_TOOLS_END_INJUSTICE', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STOLEN_TOOLS_END_UNEASY_PEACE', weight: 1 }] },
    ],
  },
  {
    id: 'STOLEN_TOOLS_END_PUBLIC_SHAME',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 30,
    title: 'Justice Revealed',
    text: 'Aelred is named a liar before the village. He confesses to confusion, claims he misremembered where he left his tools. Thornweard is vindicated, and the village sees your wisdom — you did not rush to judgment. Aelred retreats to his farm in humiliation, but the village trusts your hand.',
    portraitId: 'farmer',
    options: [
      { text: 'TRUTH PREVAILS', effects: { satisfaction: 3, authority: 2 } },
      { text: 'BE GENTLE WITH AELRED', effects: { satisfaction: 2, health: 1 } },
    ],
  },
  {
    id: 'STOLEN_TOOLS_END_MERCY',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 28,
    title: 'A Quiet Resolution',
    text: 'Aelred accepts his error privately and restores Thornweard\'s tools with apologies. The village never learns the full story, and both men thank you for discretion. Not all justice needs to be loud — sometimes mercy is the stronger path.',
    portraitId: 'farmer',
    options: [
      { text: 'DISCRETION IS WISDOM', effects: { satisfaction: 2, authority: 1 } },
      { text: 'REMIND THEM TO BE NEIGHBORLY', effects: { satisfaction: 3 } },
    ],
  },
  {
    id: 'STOLEN_TOOLS_END_INJUSTICE',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 40,
    title: 'The Wrong Man Suffers',
    text: 'Thornweard labors three months for a theft he did not commit. In the second month, Aelred\'s confusion becomes clear to all — he had misplaced the tools, not lost them to theft. The village\'s shame falls on you. Thornweard is released, but the wound of injustice does not heal.',
    portraitId: 'farmer',
    options: [
      { text: 'I WAS WRONG', effects: { satisfaction: -5, authority: -3 } },
      { text: 'COMPENSATE THORNWEARD', effects: { satisfaction: -3, gold: -10 } },
    ],
  },
  {
    id: 'STOLEN_TOOLS_END_UNEASY_PEACE',
    chainId: 'STOLEN_TOOLS',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 32,
    title: 'Neither Fully Satisfied',
    text: 'You offer Thornweard gold from the village coffers to settle the dispute. He accepts, but resentment lingers — he feels accused despite compensation. Aelred feels his loss was minimized. Both men move on, but trust in your justice is quietly questioned over ale.',
    portraitId: 'advisor',
    options: [
      { text: 'PEACE HAS ITS PRICE', effects: { satisfaction: 1, authority: -1 } },
      { text: 'INVITE THEM TO DINE', effects: { satisfaction: 2, gold: -3 } },
    ],
  },

  // === CHAIN 5: STRANGER_CAMP ===
  {
    id: 'CHAIN_STRANGER_CAMP_START',
    chainId: 'STRANGER_CAMP',
    chainRole: 'start',
    title: 'The Unknown Fire',
    text: 'A lone traveler has pitched camp two miles north of the village, beyond the tree line. Smoke rises from the clearing each dawn. No one knows his name or business. Feldric warns that strangers bring risk — disease, theft, or worse. Barnwulf counsels caution but not cruelty. "We can offer hospitality or demand he move on, my lord. The choice says much about who we are."',
    portraitId: 'military_advisor',
    options: [
      { text: 'EXPEL HIM', effects: { authority: 1, gold: -2 } },
      { text: 'INVITE HIM IN', effects: { satisfaction: 1, gold: -5 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STRANGER_CAMP_MEMBER_EXPEL', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 1, delayMaxTicks: 3, candidates: [{ requestId: 'STRANGER_CAMP_MEMBER_WELCOME', weight: 1 }] },
    ],
  },
  {
    id: 'STRANGER_CAMP_MEMBER_EXPEL',
    chainId: 'STRANGER_CAMP',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Confrontation',
    text: 'Feldric and two guards approach the camp at midday. The stranger does not resist — a weathered man with cold eyes and scarred hands, he simply watches them dismantle his fire. As he packs, he smiles and says in accented speech, "I meant no harm. But now you have made an enemy." Feldric waits for your command.',
    portraitId: 'military_advisor',
    options: [
      { text: 'LET HIM GO', effects: { satisfaction: 1, authority: 1 } },
      { text: 'DETAIN HIM', effects: { authority: 2, satisfaction: -1, gold: -3 } },
    ],
    followUps: [
      { triggerOnOptionIndex: 0, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STRANGER_CAMP_END_SAFE_DEPARTURE', weight: 1 }] },
      { triggerOnOptionIndex: 1, delayMinTicks: 2, delayMaxTicks: 4, candidates: [{ requestId: 'STRANGER_CAMP_END_BITTER_GUEST', weight: 1 }] },
    ],
  },
  {
    id: 'STRANGER_CAMP_MEMBER_WELCOME',
    chainId: 'STRANGER_CAMP',
    chainRole: 'member',
    canTriggerRandomly: false,
    title: 'The Guest Arrives',
    text: 'The stranger introduces himself as Aldren, a merchant and scholar of the old roads. He brings news of distant lands and goods — silk, spice, and stranger things. Children gather to hear his stories. But Feldric remains watchful. Aldren offers to trade and share knowledge freely. "Trust is earned, my lord," Barnwulf whispers, "but sometimes it must also be given."',
    portraitId: 'traveler',
    options: [
      { text: 'TRUST HIS WORDS', effects: { satisfaction: 2, gold: -8 } },
      { text: 'WATCH HIM CLOSELY', effects: { authority: 1, satisfaction: -1 } },
    ],
    followUps: [
      {
        triggerOnOptionIndex: 0,
        delayMinTicks: 3,
        delayMaxTicks: 5,
        candidates: [
          { requestId: 'STRANGER_CAMP_END_FORTUNE', weight: 3 },
          { requestId: 'STRANGER_CAMP_END_BETRAYAL', weight: 1 },
        ],
      },
      { triggerOnOptionIndex: 1, delayMinTicks: 3, delayMaxTicks: 5, candidates: [{ requestId: 'STRANGER_CAMP_END_CAUTIOUS_FRIEND', weight: 1 }] },
    ],
  },
  {
    id: 'STRANGER_CAMP_END_SAFE_DEPARTURE',
    chainId: 'STRANGER_CAMP',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 28,
    title: 'Gone by Dawn',
    text: 'Aldren departs peacefully, his threat nothing more than wounded pride. The village is safe, and the roads remain clear. Some speak of the decision as wise caution; others whisper that you were harsh to a harmless wanderer.',
    portraitId: 'traveler',
    options: [
      { text: 'BETTER SAFE', effects: { satisfaction: 1, authority: 1 } },
      { text: 'PERHAPS I WAS HASTY', effects: { satisfaction: 2 } },
    ],
  },
  {
    id: 'STRANGER_CAMP_END_BITTER_GUEST',
    chainId: 'STRANGER_CAMP',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 38,
    title: 'A Darker Shadow',
    text: 'Three days of questions yield no answers. Aldren remains pleasant but evasive, his past a mystery. When finally released, he departs with a cold farewell: "Remember me when sorrow comes." The village feels his departure like a curse, and sleep comes uneasily for weeks.',
    portraitId: 'traveler',
    options: [
      { text: 'GOOD RIDDANCE', effects: { satisfaction: -2, authority: -1 } },
      { text: 'SEND HIM FOOD FOR THE ROAD', effects: { satisfaction: -1, gold: -3 } },
    ],
  },
  {
    id: 'STRANGER_CAMP_END_FORTUNE',
    chainId: 'STRANGER_CAMP',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 35,
    title: 'A Fortunate Meeting',
    text: 'Aldren stays for a week, teaching the village craftsmen new techniques and trading goods at fair prices. Markweard speaks with him of old arts; the children follow him like a second father. When he finally departs, he leaves recipes, maps, and a letter promising to return. The village has gained a friend.',
    portraitId: 'merchant',
    options: [
      { text: 'FAREWELL, FRIEND', effects: { satisfaction: 4, gold: 8 } },
      { text: 'COME BACK SOON', effects: { satisfaction: 3, authority: 2 } },
    ],
  },
  {
    id: 'STRANGER_CAMP_END_BETRAYAL',
    chainId: 'STRANGER_CAMP',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 40,
    title: 'The Betrayal Revealed',
    text: 'Three days into Aldren\'s stay, a merchant from the capital arrives seeking a wanted thief — Aldren himself, who stole a shipment of silver and spices weeks past. Your welcome has harbored a criminal. The village is shaken, and your judgment questioned. Aldren is gone by nightfall, taking some of your trust with him.',
    portraitId: 'traveler',
    options: [
      { text: 'I WAS DECEIVED', effects: { satisfaction: -3, authority: -2 } },
      { text: 'SEND RIDERS AFTER HIM', effects: { satisfaction: -2, gold: -5 } },
    ],
  },
  {
    id: 'STRANGER_CAMP_END_CAUTIOUS_FRIEND',
    chainId: 'STRANGER_CAMP',
    chainRole: 'end',
    canTriggerRandomly: false,
    chainRestartCooldownTicks: 32,
    title: 'The Cautious Accord',
    text: 'Aldren remains under watch, but your suspicion proves unfounded — he is simply a wanderer with a guarded past and nothing to hide. A strange friendship blooms between caution and trust. He offers to return with goods next season, and departs with a genuine smile. Not every stranger is a threat.',
    portraitId: 'traveler',
    options: [
      { text: 'VIGILANCE PAYS OFF', effects: { satisfaction: 2, authority: 1 } },
      { text: 'TRUST EARNED', effects: { satisfaction: 3 } },
    ],
  },
];
